spring:
  datasource:
    name: test
    url: jdbc:mysql://47.99.103.238:3306/vpay?useUnicode=true&characterEncoding=UTF8&serverTimezone=UTC
    username: root
    password: mvc123$%^
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 10
    host: 47.110.144.216
    #    timeout: 1000ms
    jedis:
      pool:
        max-idle: 8
        max-active: 8
        min-idle: 0
  #    password: mvc123$%^
  mvc:
    async:
      request-timeout: 10ms
  application:
    name: CONSOLE
  aop:
    proxy-target-class: true

logging:
  level:
    org: info
    com.neemre.btcdcli4j: warn
server:
  port: 10085
  tomcat:
    max-threads: 5000
    min-spare-threads: 1000
    max-connections: 5000

hystrix.command.default.execution:
  isolation.thread.timeoutInMilliseconds: 500
  timeout.enabled: true

service:
  name: console
  expire: 6048000
  refresh: 604800000
  base64Secret: MDk4ZjZ1iY2Q0NjIxDM6M2NhZGU0ZTgzMjYyN2I0ZjY=

mybatis:
  basepackage: com.mvc.cryptovault.console.dao
  type-aliases-package: tk.mybatis.springboot.model
mapper:
  mappers:
    - com.mvc.cryptovault.console.common.MyMapper
  not-empty: false
  identity: MYSQL

cors.allowedOrigin: '*'
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/

jpush:
  secret: ceb608151cb036203ed18404
  app_key: 794af16f097626541a649ef1

eth:
  geth: http://47.75.14.213:8545

node.bitcoind.rpc.protocol: http
node.bitcoind.rpc.host: 3.112.66.210
#node.bitcoind.rpc.host: localhost
node.bitcoind.rpc.port: 12421
node.bitcoind.rpc.user: mvc-usdt
node.bitcoind.rpc.password: mvc()mvc
node.bitcoind.http.auth_scheme: Basic
node.bitcoind.notification.alert.port: 5158
node.bitcoind.notification.block.port: 5159
usdt.propId: 31


#scheduled.kline: '0 0 12 * * ?'
scheduled.kline: '*/60 * * * * ?'
scheduled.project.value: '*/60 * * * * ?'
#第三方价格获取间隔,建议为k线时间的1/4至1/2
scheduled.usdt: '*/60 * * * * ?'
#实际建议为不小于1小时(比特区块确认很慢)
scheduled.usdt.fee: '0 0 * * * ?'

#释放间隔,实际为一天一次,单位毫秒
project.frequency: 60000

kline:
  step: 10000
  start: 43200000
#  step: 3600000
#  start: 604800000

coinmarketcap.key: deebfadf-98a0-4ecf-bcc1-d3123d9b4b8e

incorme.time: